[/]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom6/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom7/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom8/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom9/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom10/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom11/']

[custom-keybindings/custom0]
binding='<Super>v'
command='/usr/bin/diodon'
name='Diodon'

[custom-keybindings/custom1]
binding='<Primary><Shift><Alt>s'
command='/home/ott/Nextcloud/MyShortcuts/open_google_scholar.sh'
name='Firefox Open Google Scholar'

[custom-keybindings/custom2]
binding='<Primary><Shift><Alt>k'
command='/home/ott/Nextcloud/MyShortcuts/open_google_keep.sh'
name='Firefox Open Google Keep'

[custom-keybindings/custom3]
binding='<Primary><Shift><Alt>l'
command='/home/ott/Nextcloud/MyShortcuts/open_google_keep_lehrstuhl.sh'
name='Firefox Open Google Keeps Lehrstuhl'

[custom-keybindings/custom4]
binding='<Primary><Shift><Alt>c'
command='/home/ott/Nextcloud/MyShortcuts/open_chat.sh'
name='Firefox Open AI Chat'

[custom-keybindings/custom5]
binding='<Primary><Shift><Alt>w'
command='/home/ott/Nextcloud/MyShortcuts/open_editor_vscode.sh'
name='Open VSCode'

[custom-keybindings/custom6]
binding='<Primary><Shift><Alt>j'
command='/home/ott/Nextcloud/MyShortcuts/open_google_docs_roboterarme.sh'
name='Firefox Open Google Docs Roboterarme'

[custom-keybindings/custom7]
binding='<Primary><Shift><Alt>e'
command='/home/ott/Nextcloud/MyShortcuts/open_editor_cursor.sh'
name='Open Cursor'

[custom-keybindings/custom8]
binding='<Primary><Shift><Alt>z'
command='/home/ott/Nextcloud/MyShortcuts/open_zotero.sh'
name='Open Zotero'

[custom-keybindings/custom9]
binding='<Primary><Shift><Alt>n'
command='/home/ott/Nextcloud/MyShortcuts/open_editor_notes_workspace_vscode.sh'
name='Open VSCode with Notes Workspace'

[custom-keybindings/custom10]
binding='<Primary><Shift><Alt>t'
command='/home/ott/Nextcloud/MyShortcuts/open_google_translate.sh'
name='Firefox Open Google Translate'

[custom-keybindings/custom11]
binding='<Primary><Shift><Alt>d'
command='/home/ott/Nextcloud/MyShortcuts/open_deepl.sh'
name='Firefox Open Deepl'

[custom-keybindings/custom12]
binding='<Primary><Shift><Alt>q'
command='/home/ott/Nextcloud/MyShortcuts/startup.sh'
name='Run computer startup script'
